[package]
name = "running-in-container"
version = "0.0.2"
edition = "2021"
authors = ["Mihai Galos <mihaigalos@gmail.com>"]
description = "ğŸ³ A rust library exporting the single function is_inside_docker to determine if application is running in a container or not."
keywords = ["docker", "podman", "dockerenv"]
repository = "https://github.com/mihaigalos/running-in-container"
license = "MIT"
